Repository lblod/ember-rdfa-editor, pull requests merged in 2021-11, with the labels that each got.

#145 Arrow handler
  addon/commands/delete-character-backwards-command.ts
  addon/commands/delete-li-backwards-command.ts
  addon/commands/delete-list-backwards-command.ts
  addon/commands/move-left-command-old.ts
  addon/commands/move-left-command.ts
  addon/commands/move-right-command-old.ts
  addon/commands/move-right-command.ts
  addon/editor/input-handlers/arrow-handler.ts
  addon/editor/input-handlers/backspace-handler-new.ts
  addon/model/cleaners/property-cleaner.ts
  addon/model/model-element.ts
  addon/model/model-position.ts
  addon/model/model-range.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/util/array-utils.ts
  addon/model/util/dom-node-finder.ts
  addon/model/util/html-utils.ts
  addon/model/util/map-utils.ts
  addon/model/util/model-node-utils.ts
  addon/model/util/model-position-utils.ts
  addon/model/util/model-range-utils.ts
  addon/model/util/model-tree-walker.ts
  addon/model/util/node-finder.ts
  addon/model/util/predicate-utils.ts
  addon/model/util/string-utils.ts
  addon/utils/ce/raw-editor.ts
  tests/unit/commands/delete-character-backwards-command-test.ts
  tests/unit/commands/delete-li-backwards-command-test.ts
  tests/unit/commands/insert-new-line-test-command.ts
  tests/unit/model/model-element-test.ts
  tests/unit/model/model-position-test.ts
  tests/unit/model/model-test.ts
  tests/unit/model/util/array-utils-test.ts
  tests/unit/model/util/model-position-utils-test.ts
  tests/unit/model/util/node-finder-test.ts
  tests/unit/model/util/tree-walker-test.ts
Labels: enhancement

#146 Backspace handler
  addon/commands/delete-character-backwards-command.ts
  addon/commands/delete-li-backwards-command.ts
  addon/commands/delete-list-backwards-command.ts
  addon/commands/delete-lump-node-backwards-command.ts
  addon/editor/input-handlers/backspace-handler-new.ts
  addon/editor/input-handlers/backspace-handler-old.ts
  addon/editor/input-handlers/backspace-handler.ts
  addon/editor/utils.ts
  addon/model/model-element.ts
  addon/model/util/constants.ts
  addon/model/util/model-node-utils.ts
  addon/model/util/model-position-utils.ts
  addon/model/util/model-range-utils.ts
  addon/utils/ce/handlers/emphasis-markdown-handler.js
  addon/utils/ce/handlers/header-markdown-handler.js
  addon/utils/ce/handlers/list-insertion-markdown-handler.js
  addon/utils/ce/list-helpers.js
  addon/utils/ce/lump-node-utils.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/plugins/br-skipping/backspace-plugin.ts
  addon/utils/plugins/contenteditable-false/backspace-plugin.ts
  addon/utils/plugins/empty-element/backspace-plugin.ts
  addon/utils/plugins/empty-text-node/backspace-plugin.ts
  addon/utils/plugins/lists/backspace-plugin.ts
  addon/utils/plugins/lump-node/backspace-plugin.ts
  addon/utils/plugins/placeholder-text/backspace-plugin.ts
  addon/utils/plugins/rdfa/backspace-plugin.ts
  addon/utils/plugins/table/backspace-plugin.ts
  tests/unit/utils/ce/next-text-node-test.ts
Labels: enhancement

#148 Delete handler
  addon/commands/delete-character-backwards-command.ts
  addon/commands/delete-character-forwards-command.ts
  addon/commands/delete-li-backwards-command.ts
  addon/commands/delete-li-forwards-command.ts
  addon/commands/delete-list-forwards-command.ts
  addon/commands/delete-lump-node-forwards-command.ts
  addon/components/ce/content-editable.ts
  addon/editor/input-handlers/delete-handler-new.ts
  addon/utils/ce/raw-editor.ts
Labels: enhancement

#178 Move get-config to real deps
  package.json
Labels: bug

#181 Add a new way to initialize plugins
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/model/controller.ts
  addon/model/model-range.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/editor-plugin.ts
  addon/utils/rdfa/rdfa-document.ts
  index.js
Labels: enhancement

#180 Add controllers
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/model/controller.ts
  addon/model/model-range.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/editor-plugin.ts
  addon/utils/rdfa/rdfa-document.ts
  index.js
Labels: enhancement

#179 Extend and improve eventbus
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/model/controller.ts
  addon/model/model-range.ts
  addon/model/mutators/batched-model-mutator.ts
  addon/model/util/constants.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/debounce.ts
  addon/utils/editor-event.ts
  addon/utils/editor-plugin.ts
  addon/utils/event-bus.ts
  addon/utils/rdfa/rdfa-document.ts
  index.js
Labels: enhancement

#182 Add a more consistent and flexible treewalker
  addon/model/model-node.ts
  addon/model/model-text.ts
  addon/model/util/constants.ts
  addon/model/util/gen-tree-walker.ts
  package.json
  tests/unit/model/utils/gen-tree-walker-test.ts
Labels: enhancement

#183 Bugfix: we should not have contenteditable tables exported outside the editor
  addon/model/writers/unpolluted-html-element-writer.ts
Labels: bug

#184 Use css variables
  CHANGELOG.md
  README.md
  addon/components/rdfa/rdfa-editor.hbs
  app/styles/deprecated/_c-alert.scss
  app/styles/deprecated/_c-article.scss
  app/styles/deprecated/_c-button.scss
  app/styles/deprecated/_c-card.scss
  app/styles/deprecated/_c-checkbox.scss
  app/styles/deprecated/_c-form.scss
  app/styles/deprecated/_c-help-text.scss
  app/styles/deprecated/_c-input.scss
  app/styles/deprecated/_c-label.scss
  app/styles/deprecated/_c-link-list.scss
  app/styles/deprecated/_c-link.scss
  app/styles/deprecated/_c-loader.scss
  app/styles/deprecated/_c-modal.scss
  app/styles/deprecated/_c-pagination.scss
  app/styles/deprecated/_p-flatpickr.scss
  app/styles/ember-rdfa-editor.scss
  app/styles/ember-rdfa-editor/_c-annotation-flag.scss
  app/styles/ember-rdfa-editor/_c-annotation-hover.scss
  app/styles/ember-rdfa-editor/_c-annotation.scss
  app/styles/ember-rdfa-editor/_c-container.scss
  app/styles/ember-rdfa-editor/_c-content.scss
  app/styles/ember-rdfa-editor/_c-dropdown.scss
  app/styles/ember-rdfa-editor/_c-editor.scss
  app/styles/ember-rdfa-editor/_c-table.scss
  app/styles/ember-rdfa-editor/_c-toast.scss
  app/styles/ember-rdfa-editor/_c-toolbar.scss
  app/styles/ember-rdfa-editor/_s-root.scss
  app/styles/ember-rdfa-editor/_s-theme.scss
  app/styles/ember-rdfa-editor/_shame.scss
  package.json
  tests/dummy/app/styles/_c-dummy.scss
  tests/dummy/app/templates/index.hbs
Labels: enhancement

#187 Add package lock
  .drone.yml
  .gitignore
  .npmrc
  CONTRIBUTING.md
  Dockerfile
  package-lock.json
Labels: internal
