Repository lblod/ember-rdfa-editor, pull requests merged in 2021-12, with the labels that each got.

#185 Add the datastore api
  README.md
  addon/components/ce/content-editable.ts
  addon/components/rdfa/rdfa-editor.hbs
  addon/config/rdfa.js
  addon/model/controller.ts
  addon/model/model-element.ts
  addon/model/model-range.ts
  addon/model/model.ts
  addon/model/util/concise-term-string.ts
  addon/model/util/constants.ts
  addon/model/util/datastore.ts
  addon/model/util/gen-tree-walker.ts
  addon/model/util/map-utils.ts
  addon/model/util/set-utils.ts
  addon/utils/ce/forgiving-action.js
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/dom-helpers.ts
  addon/utils/errors.ts
  addon/utils/rdfa-parser/active-tag.ts
  addon/utils/rdfa-parser/html-parse-listener.ts
  addon/utils/rdfa-parser/initial-context-xhtml.ts
  addon/utils/rdfa-parser/initial-context.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
  addon/utils/rdfa-parser/rdfa-pattern.ts
  addon/utils/rdfa-parser/rdfa-profile.ts
  addon/utils/rdfa-parser/util.ts
  addon/utils/rdfa/forgiving-action.js
  ember-cli-build.js
  index.js
  package-lock.json
  package.json
  tests/index.html
  tests/test-helper.js
  tests/test-helper.ts
  tests/unit/model/utils/concise-term-string-test.ts
  tests/unit/model/utils/datastore-test.ts
  tests/unit/model/utils/gen-tree-walker-test.ts
  tests/unit/utils/rdfa-parser-test.ts
  tsconfig.json
  types/graphy/memory.dataset.fast.d.ts
  types/window.d.ts
Labels: enhancement

#189 Expose termconverter on the datastore directly
  addon/model/util/datastore.ts
Labels: enhancement

#188 Add a todo test for the limitToRange method
  tests/unit/model/utils/datastore-test.ts
Labels: documentation

#190 Fire selectionChanged event when needed
  addon/utils/ce/model-selection-tracker.ts
  addon/utils/ce/raw-editor.ts
  tests/unit/model/model-selection-tracker-test.ts
Labels: bug

#191 Update ember-try to 1.4.0 and drop support for old ember versions
  .drone.yml
  config/ember-try.js
Labels: internal

#193 Update typescript-eslint packages to v5.5.0
  package-lock.json
  package.json
Labels: internal

#194 Update types for ember-test-helper
  package-lock.json
  package.json
Labels: internal

#197 Bump codemirror packages to v0.19.x
  package-lock.json
  package.json
Labels: internal

#198 Switch to using debug for logging
  addon/editor/input-handlers/paste-handler.ts
  addon/model/model.ts
  addon/utils/logging-utils.ts
  package-lock.json
  package.json
  types/window.d.ts
Labels: internal

#202 set field directly instead of using this.set
  addon/utils/ce/editor/update.js
Labels: bug

#195 Update eslint and various non-ember plugins to latest
  addon/utils/rdfa/hints-registry.js
  package-lock.json
  package.json
Labels: internal
