Repository lblod/ember-rdfa-editor, pull requests merged in 2021-08, with the labels that each got.

#138 Convert event handlers to typescript
  addon/components/ce/content-editable.ts
  addon/editor/input-handlers/arrow-handler.ts
  addon/editor/input-handlers/backspace-handler.ts
  addon/editor/input-handlers/bold-italic-underline-handler.ts
  addon/editor/input-handlers/delete-handler.ts
  addon/editor/input-handlers/disable-delete-handler.ts
  addon/editor/input-handlers/enter-handler.ts
  addon/editor/input-handlers/escape-handler.ts
  addon/editor/input-handlers/event-helpers.ts
  addon/editor/input-handlers/fallback-input-handler.ts
  addon/editor/input-handlers/handler-response.ts
  addon/editor/input-handlers/ignore-modifiers-handler.ts
  addon/editor/input-handlers/input-handler.ts
  addon/editor/input-handlers/manipulation.ts
  addon/editor/input-handlers/paste-handler.ts
  addon/editor/input-handlers/tab-handler.ts
  addon/editor/input-handlers/text-input-handler.ts
  addon/editor/input-handlers/undo-handler.ts
  addon/utils/ce/capped-history.js
  addon/utils/ce/capped-history.ts
  addon/utils/ce/flat-map.js
  addon/utils/ce/flat-map.ts
  addon/utils/ce/forgiving-action.js
  addon/utils/ce/get-rich-node-matching-dom-node.js
  addon/utils/ce/get-rich-node-matching-dom-node.ts
  addon/utils/ce/handlers/arrow-handler.js
  addon/utils/ce/handlers/delete-handler.js
  addon/utils/ce/handlers/emphasis-markdown-handler.js
  addon/utils/ce/handlers/fallback-input-handler.js
  addon/utils/ce/handlers/ignore-modifiers-handler.js
  addon/utils/ce/handlers/undo-hander.js
  addon/utils/ce/next-text-node.js
  addon/utils/ce/next-text-node.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/previous-text-node.js
  addon/utils/ce/previous-text-node.ts
  addon/utils/dom-helpers.ts
  types/lblod/marawa/rich-node.d.ts
Labels: internal

#139 Refactor commands
  addon/commands/command.ts
  addon/commands/delete-selection-command.ts
  addon/commands/indent-list-command.ts
  addon/commands/insert-html-command.ts
  addon/commands/insert-newLi-command.ts
  addon/commands/insert-newLine-command.ts
  addon/commands/insert-text-command.ts
  addon/commands/insert-xml-command.ts
  addon/commands/make-list-command.ts
  addon/commands/remove-list-command.ts
  addon/commands/unindent-list-command.ts
  addon/model/cleaners/list-cleaner.ts
  addon/model/model-element.ts
  addon/model/model-node.ts
  addon/model/model-position.ts
  addon/model/model-selection.ts
  addon/model/model-table.ts
  addon/model/model.ts
  addon/model/operations/insert-operation.ts
  addon/model/util/constants.ts
  addon/model/util/model-node-utils.ts
  addon/model/util/model-range-utils.ts
  addon/model/util/model-tree-walker.ts
  addon/model/util/predicate-utils.ts
  addon/utils/errors.ts
  tests/unit/commands/insert-new-li-command-test.ts
  tests/unit/commands/make-list-command-test.ts
  tests/unit/commands/remove-list-command-test.ts
  tests/unit/model/model-node-test.ts
  tests/utilities/model-test-context.ts
Labels: bug, internal

#154 Collapse the selection upon initializing the editor
  addon/utils/rdfa/rdfa-document.ts
Labels: enhancement

#147 Convert list helpers
  addon/commands/command.ts
  addon/editor/utils.ts
  addon/utils/ce/list-helpers.js
  addon/utils/ce/list-helpers.ts
  addon/utils/ce/next-text-node.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/previous-text-node.ts
  addon/utils/dom-helpers.ts
  addon/utils/html-input-parser.ts
  addon/utils/plugins/lists/tab-input-plugin.ts
  addon/utils/plugins/placeholder-text/backspace-plugin.ts
Labels: internal

#150 Fix insert XML
  addon/commands/insert-xml-command.ts
  addon/model/readers/xml-reader.ts
  addon/model/util/xml-utils.ts
  addon/utils/rdfa/rdfa-document.ts
  tests/dummy/app/controllers/index.ts
Labels: bug

#151 Disable dragstart
  addon/components/ce/content-editable.hbs
  addon/components/ce/content-editable.ts
Labels: enhancement
