Repository lblod/ember-rdfa-editor, pull requests merged in 2021-07, with the labels that each got.

#125 Add lerna changelog config
  .release-it.json
  CHANGELOG.md
  package.json
Labels: internal

#126 Commands testing + implementation xml table reader
  addon/model/readers/xml-node-reader.ts
  addon/model/readers/xml-table-reader.ts
  tests/unit/commands/insert-table-command-test.ts
  tests/unit/commands/insert-table-row-above-command-test.ts
  tests/unit/commands/insert-table-row-below-command-test.ts
  tests/unit/commands/insert-xml-command-test.ts
  tests/unit/model/cleaners/list-cleaner-test.ts
  tests/unit/model/mutators/immediate-model-mutator-test.ts
Labels: internal

#127 Changes to getFromSelection methods in ModelTable
  addon/model/model-table.ts
Labels: internal

#130 Feature/event bus
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/event-bus.ts
  addon/utils/rdfa/rdfa-document.ts
Labels: bug, enhancement

#124 move the dispatcher service inside the editor addon
  app/services/rdfa-editor-dispatcher.js
  lib/plugin-system-dispatcher/addon/services/rdfa-editor-dispatcher.js
  lib/plugin-system-dispatcher/index.js
  lib/plugin-system-dispatcher/package.json
  package.json
Labels: internal

#128 Table column and row commands testing
  tests/unit/commands/insert-table-column-after-command-test.ts
  tests/unit/commands/insert-table-column-before-command-test.ts
  tests/unit/commands/remove-table-column-command-test.ts
  tests/unit/commands/remove-table-command-test.ts
  tests/unit/commands/remove-table-row-command-test.ts
Labels: internal

#129 Remove table when last row or column gets removed
  addon/commands/remove-table-column-command.ts
  addon/commands/remove-table-row-command.ts
  addon/model/model-table.ts
  tests/unit/commands/remove-table-column-command-test.ts
  tests/unit/commands/remove-table-row-command-test.ts
Labels: bug

#134 Fix cursor behavior when using table dropdown menu
  addon/components/rdfa/dropdown-item.hbs
  addon/components/rdfa/dropdown-item.ts
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/toolbar-dropdown.hbs
  addon/components/rdfa/toolbar-dropdown.js
  app/components/rdfa/dropdown-item.js
Labels: bug

#132 Cut command
  addon/commands/command.ts
  addon/commands/delete-selection-command.ts
  addon/components/ce/content-editable.js
  addon/editor/input-handlers/cut-handler.ts
  addon/model/model-element.ts
  addon/model/model-node.ts
  addon/model/model-position.ts
  addon/model/model-table.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/util/model-node-utils.ts
  addon/model/util/xml-utils.ts
  addon/model/writers/html-export-writer.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
  config/environment.js
  tests/unit/commands/delete-selection-command-test.ts
  tests/unit/commands/insert-table-column-after-command-test.ts
  tests/unit/model/mutators/immediate-model-mutator-test.ts
  types/window.d.ts
Labels: enhancement

#137 Move paste handler to its own input handler
  addon/components/ce/content-editable.js
  addon/editor/input-handlers/input-handler.ts
  addon/editor/input-handlers/paste-handler.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/html-input-parser.js
  addon/utils/html-input-parser.ts
  package.json
Labels: internal
