Repository lblod/ember-rdfa-editor, pull requests merged in 2022-10, with the labels that each got.

#385 Ensure dom nodes are correctly converted to model nodes
  addon/core/view/index.ts
  addon/utils/dom-helpers.ts
Labels: bug

#386 Fix: inline component selection issues
  addon/commands/insert-component-command.ts
  addon/core/model/model-position.ts
  addon/input/input-handler.ts
  addon/utils/dom-helpers.ts
  addon/utils/mutation-helpers.ts
  tests/dummy/app/components/inline-components/counter.hbs
  tests/dummy/app/components/inline-components/counter.ts
  tests/dummy/app/components/inline-components/dropdown.hbs
  tests/dummy/app/components/inline-components/dropdown.ts
  tests/dummy/app/components/rdfa-ic-plugin-insert.hbs
  tests/dummy/app/components/rdfa-ic-plugin-insert.ts
  tests/dummy/app/testplugin/dummy-plugin.ts
  tests/dummy/app/testplugin/models/inline-components/counter.ts
  tests/dummy/app/testplugin/models/inline-components/dropdown.ts
Labels: bug

#384 Chore/cleanup feature flags
  README.md
  config/environment.js
Labels: internal

#389 Enable html pasting by passing a property to the editor component
  README.md
  addon/components/ce/content-editable.hbs
  addon/components/rdfa/rdfa-editor-with-debug.hbs
  addon/components/rdfa/rdfa-editor-with-debug.ts
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/input/input-handler.ts
  config/environment.js
Labels: bug, breaking

#390 Feature: allow for plugins to reload dynamically
  addon/components/ce/content-editable.hbs
  addon/components/ce/content-editable.ts
  addon/components/rdfa/rdfa-editor.ts
  addon/core/controllers/controller.ts
  addon/core/controllers/view-controller.ts
  addon/core/model/editor-plugin.ts
  addon/core/state/steps/plugin-step.ts
  addon/core/state/steps/step.ts
  addon/core/state/transaction.ts
  addon/core/view/index.ts
  addon/plugins/anchor/anchor.ts
  addon/plugins/basic-styles/basic-styles.ts
  addon/plugins/list/list.ts
  addon/plugins/lump-node/lump-node.ts
  addon/plugins/placeholder/placeholder.ts
  addon/plugins/rdfa-confirmation/rdfa-confirmation.ts
  addon/plugins/show-active-rdfa/show-active-rdfa.ts
  addon/plugins/table/table.ts
  tests/dummy/app/components/code-mark-plugin/toolbar-button.hbs
  tests/dummy/app/components/code-mark-plugin/toolbar-button.ts
  tests/dummy/app/components/inline-components-plugin/counter.hbs
  tests/dummy/app/components/inline-components-plugin/counter.ts
  tests/dummy/app/components/inline-components-plugin/dropdown.hbs
  tests/dummy/app/components/inline-components-plugin/dropdown.ts
  tests/dummy/app/components/inline-components-plugin/rdfa-ic-plugin-insert.hbs
  tests/dummy/app/components/inline-components-plugin/rdfa-ic-plugin-insert.ts
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/dummy-plugins/code-mark-plugin/code-plugin.ts
  tests/dummy/app/dummy-plugins/code-mark-plugin/marks/code-mark.ts
  tests/dummy/app/dummy-plugins/highlight-plugin/highlight-plugin.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/inline-components-plugin.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/models/inline-components/counter.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/models/inline-components/dropdown.ts
  tests/dummy/app/initializers/dummy-plugin.ts
  tests/dummy/app/initializers/dummy-plugins.ts
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/index.hbs
  tests/dummy/app/testplugin/dummy-plugin.ts
Labels: enhancement, breaking

#396 Fix issue with computing differences on transaction dispatch
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/inline-component-manager.ts
  addon/components/rdfa/rdfa-editor.ts
  addon/core/controllers/controller.ts
  addon/core/state/index.ts
  addon/core/state/transaction.ts
  addon/core/view/index.ts
  addon/input/insert.ts
  addon/input/keymap.ts
  addon/plugins/show-active-rdfa/show-active-rdfa.ts
  tests/dummy/app/components/code-mark-plugin/toolbar-button.ts
  tests/dummy/app/dummy-plugins/highlight-plugin/highlight-plugin.ts
  tests/test-utils.ts
Labels: bug

#398 Bugfix: inline component reload
  addon/components/rdfa/rdfa-editor.hbs
  addon/model/inline-components/model-inline-component.ts
Labels: bug

#397 TEDI: live mark set rework
  addon/components/rdfa/rdfa-editor.ts
  addon/core/controllers/controller.ts
  addon/core/controllers/view-controller.ts
  addon/core/model/marks/live-mark-set.ts
  addon/core/state/steps/step.ts
  addon/plugins/live-mark-set/commands/live-mark-rule-command.ts
  addon/plugins/live-mark-set/live-mark-set.ts
  addon/utils/editor-event.ts
Labels: internal, breaking

#410 feature/simple positions
  addon/core/model/nodes/model-node.ts
  addon/core/model/simple-position.ts
  addon/utils/errors.ts
  addon/utils/unwrap.ts
  tests/unit/model/simple-position-test.ts
Labels: enhancement
