Repository lblod/ember-rdfa-editor, pull requests merged in 2022-09, with the labels that each got.

#312 Replace selection arg by range arg in insert-component-command
  addon/commands/insert-component-command.ts
Labels: bug, breaking

#313 Improved inline components management
  addon/commands/insert-component-command.ts
  addon/components/rdfa/rdfa-editor.ts
  addon/model/controller.ts
  addon/model/inline-components/inline-components-registry.ts
  addon/model/model.ts
  addon/model/readers/html-inline-component-reader.ts
  addon/utils/ce/raw-editor.ts
Labels: enhancement

#316 Fix getRdfaAttributes() behaviour
  addon/model/model-element.ts
  addon/model/util/rdfa-utils.ts
Labels: bug

#311 RFC: Transactional Edits
  rfcs/transactional-edits.md
Labels: documentation

#314 RFC: ModelNode rework
  rfcs/model.md
Labels: documentation

#318 Modify emit order of selectionChangedEvents and modelReadEvents
  addon/model/model.ts
Labels: bug

#319 Fix/ember appuniversum
  .drone.yml
  app/styles/deprecated/_c-alert.scss
  app/styles/deprecated/_c-article.scss
  app/styles/deprecated/_c-button.scss
  app/styles/deprecated/_c-card.scss
  app/styles/deprecated/_c-checkbox.scss
  app/styles/deprecated/_c-form.scss
  app/styles/deprecated/_c-help-text.scss
  app/styles/deprecated/_c-input.scss
  app/styles/deprecated/_c-label.scss
  app/styles/deprecated/_c-link-list.scss
  app/styles/deprecated/_c-link.scss
  app/styles/deprecated/_c-loader.scss
  app/styles/deprecated/_c-modal.scss
  app/styles/deprecated/_c-pagination.scss
  app/styles/deprecated/_p-flatpickr.scss
  app/styles/deprecated/_u-align-text.scss
  app/styles/deprecated/_u-hide.scss
  app/styles/deprecated/_u-word-break.scss
  app/styles/ember-rdfa-editor.scss
  app/styles/ember-rdfa-editor/_a-custom-components.scss
  app/styles/ember-rdfa-editor/_a-dummy.scss
  index.js
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
Labels: breaking

#341 Update to new codemirror name and fix associated problems
  addon/components/rdfa/rdfa-editor-with-debug.ts
  addon/model/util/datastore/graphy-dataset.ts
  package-lock.json
  package.json
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/routes/index.ts
Labels: internal

#376 fix(selection-handler): handle cases where selection is empty
  addon/components/rdfa/toolbar-dropdown.ts
Labels: bug

#358 Introduction of a MarksManager
  addon/commands/remove-mark-from-node-command.ts
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/core/controllers/controller.ts
  addon/core/controllers/view-controller.ts
  addon/core/model/marks/mark.ts
  addon/core/model/marks/marks-manager.ts
  addon/core/model/marks/marks-registry.ts
  addon/core/model/nodes/model-text.ts
  addon/core/model/operations/insert-operation.ts
  addon/core/model/operations/insert-text-operation.ts
  addon/core/model/operations/mark-operation.ts
  addon/core/model/operations/move-operation.ts
  addon/core/model/operations/operation.ts
  addon/core/model/operations/remove-operation.ts
  addon/core/model/operations/split-operation.ts
  addon/core/model/readers/html-reader.ts
  addon/core/model/readers/html-text-reader.ts
  addon/core/model/readers/xml-text-reader.ts
  addon/core/state/index.ts
  addon/core/state/transaction.ts
  addon/utils/array-utils.ts
  tests/dummy/app/testplugin/dummy-plugin.ts
  tests/test-utils.ts
  tests/unit/model/marks/marks-manager-test.ts
  tests/unit/model/model-text-test.ts
Labels: enhancement

#365 Fix issue with inline components not being persisted correctly across reloads
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/inline-component-manager.hbs
  addon/components/rdfa/inline-component-manager.ts
Labels: bug

#373 Fix: view to model behaviour
  addon/core/view/index.ts
  tests/unit/model/model-element-test.ts
  tests/unit/model/model-position-test.ts
Labels: bug
