Repository lblod/ember-rdfa-editor, pull requests merged in 2022-03, with the labels that each got.

#235 Fix list indentation
  app/styles/ember-rdfa-editor/_c-editor.scss
Labels: bug

#234 Bug/mark attribute rendering
  addon/model/mark.ts
  tests/unit/commands/match-text-command-test.ts
Labels: bug

#233 Fix bug with predicate node generation
  addon/model/mark.ts
  addon/model/util/datastore/datastore.ts
  tests/unit/commands/match-text-command-test.ts
Labels: bug

#238 bump ember-truth-helpers to 3.0.0
  package-lock.json
  package.json
Labels: internal

#241 bump ember-cli-app-version to 5.0.0
  package-lock.json
  package.json
Labels: internal

#240 add embroider test scenarios to ember try
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
Labels: internal, prio:low

#242 dev packages spring cleaning
  package-lock.json
  package.json
Labels: internal

#236 Implement incremental dom writing
  .drone.yml
  addon/commands/insert-text-command.ts
  addon/commands/insert-xml-command.ts
  addon/components/ce/content-editable.ts
  addon/components/rdfa/toolbar-dropdown.js
  addon/editor/input-handlers/arrow-handler.ts
  addon/editor/input-handlers/backspace-handler.ts
  addon/editor/input-handlers/delete-handler.ts
  addon/editor/input-handlers/fallback-input-handler.ts
  addon/editor/input-handlers/tab-handler.ts
  addon/editor/input-handlers/text-input-handler.ts
  addon/editor/input-handlers/undo-handler.ts
  addon/model/mark.ts
  addon/model/model-element.ts
  addon/model/model-node.ts
  addon/model/model-text.ts
  addon/model/model.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/node-view.ts
  addon/model/operations/operation-algorithms.ts
  addon/model/readers/html-element-reader.ts
  addon/model/readers/html-list-reader.ts
  addon/model/readers/html-node-reader.ts
  addon/model/readers/html-reader.ts
  addon/model/readers/html-table-reader.ts
  addon/model/readers/html-text-reader.ts
  addon/model/readers/selection-reader.ts
  addon/model/readers/xml-element-reader.ts
  addon/model/readers/xml-node-reader.ts
  addon/model/readers/xml-text-reader.ts
  addon/model/util/model-node-utils.ts
  addon/model/util/set-utils.ts
  addon/model/util/types.ts
  addon/model/writers/html-element-writer.ts
  addon/model/writers/html-export-writer.ts
  addon/model/writers/html-text-writer.ts
  addon/model/writers/html-writer.ts
  addon/model/writers/selection-writer.ts
  addon/model/writers/unpolluted-html-text-writer.ts
  addon/model/writers/xml-node-writer.ts
  addon/model/writers/xml-text-writer.ts
  addon/utils/plugins/table/tab-input-plugin.ts
  tests/unit/model/marks-test.ts
  tests/unit/model/model-node-test.ts
  tests/unit/model/operations/insert-operation-test.ts
  tests/unit/model/operations/move-operation-test.ts
  tests/unit/model/twoway-conversion-test.ts
  tests/unit/model/writers/selection-writer-test.ts
Labels: enhancement

#237 Fixing unindenting
  addon/commands/indent-list-command.ts
  addon/commands/unindent-list-command.ts
Labels: bug

#239 execute undo on VDOM
  addon/commands/insert-xml-command.ts
  addon/commands/undo-command.ts
  addon/editor/input-handlers/backspace-handler.ts
  addon/editor/input-handlers/fallback-input-handler.ts
  addon/editor/input-handlers/undo-handler.ts
  addon/model/model.ts
  addon/model/util/set-node-and-child-dirty.ts
  addon/utils/ce/list-helpers.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
Labels: enhancement
