Repository lblod/ember-rdfa-editor, pull requests merged in 2022-02, with the labels that each got.

#215 Dont update selection on setting marks
  addon/commands/add-mark-to-range-command.ts
  addon/commands/remove-mark-from-range-command.ts
  addon/commands/text-properties/set-text-property-command.ts
  addon/utils/ce/pernet-raw-editor.ts
Labels: bug

#216 Don't export the debug component
  README.md
  app/components/rdfa/rdfa-editor-with-debug.js
Labels: bug, breaking

#214 Expose query utility on markset
  addon/commands/node-properties/add-type-command.ts
  addon/commands/node-properties/remove-type-command.ts
  addon/commands/node-properties/set-property-command.ts
  addon/model/mark.ts
  addon/model/model-element.ts
  addon/model/model-node.ts
  addon/model/model-selection.ts
  addon/model/model-text.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/readers/xml-text-reader.ts
  addon/model/util/constants.ts
  addon/model/util/hash-set.ts
Labels: enhancement

#220 Fix dummy component import
  tests/dummy/app/components/rdfa-editor-with-debug.js
  tests/dummy/app/templates/index.hbs
Labels: bug

#218 Ember-appuniversum upgrade > 0.11.0
  app/styles/deprecated/_c-alert.scss
  app/styles/deprecated/_c-button.scss
  app/styles/ember-rdfa-editor.scss
  app/styles/ember-rdfa-editor/_c-annotation.scss
  app/styles/ember-rdfa-editor/_c-content.scss
  app/styles/ember-rdfa-editor/_c-dropdown.scss
  app/styles/ember-rdfa-editor/_c-editor.scss
  app/styles/ember-rdfa-editor/_s-root.scss
  ember-cli-build.js
  index.js
  package-lock.json
  package.json
Labels: internal

#219 Implement text-matching command
  addon/commands/match-text-command.ts
  addon/model/model-range.ts
  addon/model/util/gen-tree-walker.ts
  addon/utils/ce/raw-editor.ts
  tests/unit/commands/match-text-command-test.ts
Labels: enhancement

#222 Provide a single stylesheet for the dummy app
  app/styles/ember-rdfa-editor.scss
  app/styles/ember-rdfa-editor/_a-custom-components.scss
  app/styles/ember-rdfa-editor/_a-dummy.scss
  app/styles/ember-rdfa-editor/_c-annotation-hover.scss
  app/styles/ember-rdfa-editor/_c-annotation.scss
  app/styles/ember-rdfa-editor/_c-dummy.scss
  app/styles/ember-rdfa-editor/custom-components.scss
  package-lock.json
  package.json
  tests/dummy/app/styles/_g-reset.scss
  tests/dummy/app/styles/_legacy.scss
  tests/dummy/app/styles/app.scss
Labels: internal, breaking

#211 Improve datastore interface
  addon/components/ce/content-editable.ts
  addon/model/controller.ts
  addon/model/model-range.ts
  addon/model/operations/operation.ts
  addon/model/readers/xml-element-reader.ts
  addon/model/readers/xml-text-reader.ts
  addon/model/util/array-utils.ts
  addon/model/util/datastore/datastore.ts
  addon/model/util/datastore/graphy-dataset.ts
  addon/model/util/datastore/result-set.ts
  addon/model/util/datastore/term-mapping.ts
  addon/model/util/datastore/term-spec.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/event-bus.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
  package-lock.json
  package.json
  tests/test-helper.ts
  tests/unit/model/model-range-context-test.ts
  tests/unit/model/utils/datastore-test.ts
  tests/unit/utils/rdfa-parser-test.ts
Labels: enhancement

#224 Add isEmpty utility method on resultset and term-mapping
  addon/model/util/datastore/result-set.ts
  addon/model/util/datastore/term-mapping.ts
Labels: enhancement

#225 Make backspace handler trigger contentchanged event
  addon/editor/input-handlers/backspace-handler.ts
  addon/model/marks-registry.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/editor-event.ts
Labels: bug
