Repository lblod/ember-rdfa-editor, pull requests merged in 2022-12, with the labels that each got.

#492 feature(dev): add devtools
  addon/components/rdfa/rdfa-editor-with-debug.hbs
  addon/components/rdfa/rdfa-editor-with-debug.ts
  addon/components/rdfa/rdfa-editor.ts
  addon/core/prosemirror.ts
  index.js
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#500 fix(initialization): emit a selectionchanged after init
  addon/utils/ce/raw-editor.ts
Labels: bug

#499 fix(initialization): emit a selectionchanged after init
  addon/utils/ce/raw-editor.ts
Labels: bug

#495 Add resolved-positions to prose-store
  addon/core/prosemirror.ts
  addon/utils/datastore/datastore.ts
  addon/utils/position-utils.ts
Labels: enhancement

#502 Cleanup unused code, tighten linting, fix linting
  .eslintrc.js
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/rdfa-editor-with-debug.ts
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/core/prosemirror.ts
  addon/nodes/list-nodes.ts
  addon/utils/datastore/datastore.ts
  addon/utils/option.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
  addon/utils/unwrap.ts
  tests/dummy/app/dummy-plugins/highlight-plugin/index.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/inline-component-models/card.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/inline-component-models/counter.ts
  tests/integration/input-handlers/delete-handler-test.ts
  tests/test-helper.ts
  tests/unit/model/utils/datastore-test.ts
Labels: internal

#451 GN-3716 - Improve copy/paste from word
  addon/editor/input-handlers/paste-handler.ts
  addon/plugins/lump-node/lump-node.ts
  addon/utils/ce/paste-handler-func.ts
  addon/utils/ce/paste-handler-helper-functions/buildList.ts
  addon/utils/ce/paste-handler-helper-functions/cleanCrLf.ts
  addon/utils/ce/paste-handler-helper-functions/cleanDocx.ts
  addon/utils/ce/paste-handler-helper-functions/cleanEmptyElements.ts
  addon/utils/ce/paste-handler-helper-functions/cleanLinkElements.ts
  addon/utils/ce/paste-handler-helper-functions/cleanListElements.ts
  addon/utils/ce/paste-handler-helper-functions/getListContentHtml.ts
  addon/utils/ce/paste-handler-helper-functions/getListLevel.ts
  addon/utils/ce/paste-handler-helper-functions/index.ts
  addon/utils/ce/paste-handler-helper-functions/isComment.ts
  addon/utils/ce/paste-handler-helper-functions/isFragmentHref.ts
  addon/utils/ce/paste-handler-helper-functions/isList.ts
  addon/utils/ce/paste-handler-helper-functions/isOrderedList.ts
  addon/utils/ce/paste-handler-helper-functions/parseHtmlElement.ts
  addon/utils/ce/paste-handler-helper-functions/postCleanHtml.ts
  addon/utils/ce/paste-handler-helper-functions/preCleanHtml.ts
  addon/utils/ce/paste-handler-helper-functions/removeHtmlSurroundings.ts
  addon/utils/ce/paste-handler-helper-functions/removeNodesBetweenComments.ts
  addon/utils/ce/paste-handler-helper-functions/traverse.ts
  addon/utils/ce/paste-handler-helper-functions/traverseComments.ts
  addon/utils/ce/paste-handler-helper-functions/traverseElements.ts
  addon/utils/ce/paste-handler-helper-functions/unwrapElement.ts
  tests/unit/utils/convert-generic-html-test.ts
  tests/unit/utils/convert-ms-word-html-test.ts
Labels: enhancement

#508 bug(datastore): guarantee reference stability for datastore data
  addon/core/prosemirror.ts
  addon/utils/datastore/datastore.ts
  addon/utils/reference-manager.ts
Labels: bug

#509 feature(datastore): implement ds as a plugin
  addon/core/prosemirror.ts
  addon/plugins/datastore/index.ts
  app/commands/insert-html-command.js
  app/commands/type-commands.js
  app/plugin/datastore.js
  app/plugin/placeholder.js
Labels: enhancement

#513 Addition of utility functions which allow for searching nodes in a specific range or with a specific condition
  addon/utils/position-utils.ts
  tests/test-helper.ts
  tests/test-utils.ts
  tests/unit/utils/position-utils-test.ts
Labels: enhancement

#507 Rework placeholders
  addon/nodes/index.ts
  addon/nodes/placeholder.ts
  addon/plugins/placeholder/index.ts
  app/styles/ember-rdfa-editor/_c-annotation.scss
  tests/dummy/app/controllers/index.ts
Labels: enhancement

#515 fix/list behavior - rdfa as marks
  addon/components/editor-components/slot.hbs
  addon/components/plugins/table/table-menu.hbs
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/rdfa-editor.hbs
  addon/core/prosemirror.ts
  addon/core/schema.ts
  addon/marks/link.ts
  addon/nodes/heading.ts
  addon/nodes/inline-rdfa.ts
  addon/nodes/paragraph.ts
  addon/nodes/placeholder.ts
  addon/plugins/datastore/index.ts
  addon/utils/datastore/prose-store.ts
  addon/utils/option.ts
  addon/utils/position-utils.ts
  addon/utils/rdfa-utils.ts
  app/styles/ember-rdfa-editor.scss
  tests/dummy/app/controllers/index.ts
  tests/unit/utils/position-utils-test.ts
Labels: breaking

#516 Fix table insertion menu and keymapping
  addon/components/plugins/table/table-menu.ts
  addon/index.ts
  addon/plugins/table/index.ts
  addon/plugins/table/table-nodes.ts
  tests/dummy/app/controllers/index.ts
Labels: enhancement

#517 Make mark buttons and commands work like they used to
  addon/commands/toggle-mark-add-first.ts
  addon/core/keymap.ts
  addon/core/prosemirror.ts
Labels: enhancement

#518 fix table menu items not appearing when in table
  addon/commands/toggle-mark-add-first.ts
  addon/components/plugins/table/table-menu.ts
  addon/components/rdfa/editor-toolbar.ts
Labels: bug
