Repository lblod/ember-rdfa-editor, pull requests merged in 2022-04, with the labels that each got.

#244 ran npm update
  addon/model/util/datastore/graphy-dataset.ts
  package-lock.json
  package.json
Labels: internal

#247 convert newlines to br elements when inserting text
  addon/commands/insert-text-command.ts
  tests/unit/commands/insert-text-command-test.ts
Labels: bug

#245 replace all special spaces when regular spaces when parsing html
  addon/utils/html-input-parser.ts
  tests/unit/utils/html-input-parser-test.ts
Labels: enhancement

#246 Implement self-updating regex-constrained sets of marks
  addon/commands/insert-newLi-command.ts
  addon/commands/insert-text-command.ts
  addon/commands/match-text-command.ts
  addon/commands/remove-mark-from-range-command.ts
  addon/commands/remove-marks-from-ranges-command.ts
  addon/components/rdfa/editor-toolbar.ts
  addon/model/controller.ts
  addon/model/live-mark-set.ts
  addon/model/mark.ts
  addon/model/marks-registry.ts
  addon/model/model-range.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/operations/insert-operation.ts
  addon/model/operations/insert-text-operation.ts
  addon/model/operations/mark-operation.ts
  addon/model/operations/move-operation.ts
  addon/model/operations/operation-algorithms.ts
  addon/model/operations/operation.ts
  addon/model/operations/split-operation.ts
  addon/model/range-mapper.ts
  addon/model/readers/html-span-reader.ts
  addon/model/util/constants.ts
  addon/model/util/datastore/datastore.ts
  addon/model/util/datastore/graphy-dataset.ts
  addon/model/util/datastore/term-mapping.ts
  addon/model/util/gen-tree-walker.ts
  addon/model/util/map-utils.ts
  addon/model/util/set-utils.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/editor-event.ts
  addon/utils/match-text.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
  tests/unit/commands/insert-new-li-command-test.ts
  tests/unit/commands/insert-text-command-test.ts
  tests/unit/model/mutators/immediate-model-mutator-test.ts
  tests/unit/model/operations/algorithms/insert-algorithm-test.ts
  tests/unit/model/operations/algorithms/operation-algorithms-test.ts
  tests/unit/model/operations/algorithms/remove-algorithm-test.ts
  tests/unit/model/operations/algorithms/split-algorithm-test.ts
  tests/unit/model/operations/insert-operation-test.ts
  tests/unit/model/operations/move-operation-test.ts
  tests/unit/model/operations/split-operation-test.ts
  types/graphy/memory.dataset.fast.d.ts
Labels: enhancement, breaking

#251 Fix toolbar marks using wrong command arguments
  addon/components/rdfa/editor-toolbar.ts
Labels: bug

#253 More consice removing of RDFa type
  addon/commands/node-properties/remove-type-command.ts
Labels: bug

#232 Breaking/remove old plugin wiring
  README.md
  addon/components/ce/content-editable.ts
  addon/components/rdfa/editor-suggested-hints.hbs
  addon/components/rdfa/hints-registry-debugger.hbs
  addon/components/rdfa/hints-registry-debugger.js
  addon/components/rdfa/load-monitor.hbs
  addon/components/rdfa/load-monitor.js
  addon/components/rdfa/rdfa-context-debugger.hbs
  addon/components/rdfa/rdfa-context-debugger.js
  addon/components/rdfa/rdfa-editor-debugger.hbs
  addon/components/rdfa/rdfa-editor-debugger.js
  addon/components/rdfa/rdfa-editor-with-debug.hbs
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/editor/input-handlers/paste-handler.ts
  addon/editor/pernet.ts
  addon/utils/ce/editor.js
  addon/utils/ce/editor/operation.js
  addon/utils/ce/editor/select.js
  addon/utils/ce/editor/selection-utils.js
  addon/utils/ce/editor/triplestore.js
  addon/utils/ce/editor/update.js
  addon/utils/ce/node-walker.js
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/rich-node-tree-modification.js
  addon/utils/dom-helpers.ts
  addon/utils/is-empty.js
  addon/utils/normalize-location.js
  addon/utils/plugin-editor-api.js
  addon/utils/plugin-hints-registry-api.js
  addon/utils/rdfa/event-processor.ts
  addon/utils/rdfa/hints-registry.js
  addon/utils/rdfa/rdfa-context-scanner.js
  addon/utils/rdfa/rdfa-rich-node-helpers.js
  addon/utils/triples-in-selection.js
  app/components/rdfa/editor-suggested-hints.js
  app/components/rdfa/hints-registry-debugger.js
  app/components/rdfa/load-monitor.js
  app/components/rdfa/rdfa-context-debugger.js
  app/components/rdfa/rdfa-editor-debugger.js
  app/services/rdfa-editor-dispatcher.js
Labels: breaking

#249 Improved table insert, and column and row insert
  addon/components/rdfa/dropdown-item.hbs
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/toolbar-dropdown.hbs
  addon/model/model-table.ts
  addon/utils/debounce.ts
  app/styles/deprecated/_c-input.scss
  app/styles/ember-rdfa-editor/_c-dropdown.scss
  app/styles/ember-rdfa-editor/_c-toolbar.scss
  package-lock.json
  package.json
  tests/unit/commands/insert-table-column-after-command-test.ts
  tests/unit/commands/insert-table-column-before-command-test.ts
  tests/unit/commands/insert-table-command-test.ts
  tests/unit/commands/insert-table-row-above-command-test.ts
  tests/unit/commands/insert-table-row-below-command-test.ts
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#255 improve whitespace collapsing
  addon/model/readers/html-text-reader.ts
  addon/model/util/constants.ts
  addon/utils/whitespace-collapsing.ts
  tests/unit/utils/whitespace-collapsing-test.ts
Labels: bug

#254 Fixed weird cases where the unindent button appeared without being available
  addon/commands/indent-list-command.ts
  addon/commands/unindent-list-command.ts
  addon/model/util/model-range-utils.ts
Labels: bug

#259 Fix collapsed selections not detecting marks correctly
  addon/commands/add-mark-to-range-command.ts
  addon/commands/add-mark-to-selection-command.ts
  addon/commands/insert-text-command.ts
  addon/commands/remove-mark-command.ts
  addon/commands/remove-mark-from-selection-command.ts
  addon/components/rdfa/editor-toolbar.ts
  addon/editor/input-handlers/bold-italic-underline-handler.ts
  addon/model/mark.ts
  addon/model/marks-registry.ts
  addon/model/model-range.ts
  addon/model/model-selection.ts
  addon/model/model.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/operations/insert-text-operation.ts
  addon/model/operations/mark-operation.ts
  addon/model/readers/selection-reader.ts
  addon/model/util/gen-tree-walker.ts
  addon/utils/ce/model-selection-tracker.ts
  addon/utils/ce/raw-editor.ts
  tests/unit/model/mutators/immediate-model-mutator-test.ts
Labels: bug

#261 Fix textsearch on quads defined outside the root element
  addon/model/model-range.ts
  addon/model/util/datastore/datastore.ts
Labels: bug

#258 Fix bug that selection was wrong when creating en empty list
  addon/commands/make-list-command.ts
  tests/unit/commands/make-list-command-test.ts
Labels: bug

#260 Fixed bug with making list at the end of the document
  addon/model/util/gen-tree-walker.ts
Labels: bug

#256 widget redesign
  addon/components/rdfa/plugin-wrapper.hbs
  addon/components/rdfa/plugin-wrapper.ts
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  addon/model/controller.ts
  addon/utils/ce/raw-editor.ts
  app/components/rdfa/plugin-wrapper.js
  app/styles/ember-rdfa-editor/_c-container.scss
  app/styles/ember-rdfa-editor/_c-editor-hints.scss
  app/styles/ember-rdfa-editor/_c-toast.scss
  app/styles/ember-rdfa-editor/_shame.scss
  app/utils/widget-map.js
  package-lock.json
  package.json
Labels: enhancement

#257 Enhancement/better handlers
  addon/commands/node-properties/remove-property-command.ts
  addon/components/ce/content-editable.ts
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/rdfa-editor.ts
  addon/editor/input-handlers/arrow-handler.ts
  addon/editor/input-handlers/backspace-handler.ts
  addon/editor/input-handlers/bold-italic-underline-handler.ts
  addon/editor/input-handlers/cut-copy-handler.ts
  addon/editor/input-handlers/delete-handler.ts
  addon/editor/input-handlers/disable-delete-handler.ts
  addon/editor/input-handlers/enter-handler.ts
  addon/editor/input-handlers/escape-handler.ts
  addon/editor/input-handlers/fallback-input-handler.ts
  addon/editor/input-handlers/ignore-modifiers-handler.ts
  addon/editor/input-handlers/input-handler.ts
  addon/editor/input-handlers/manipulation.ts
  addon/editor/input-handlers/paste-handler.ts
  addon/editor/input-handlers/tab-handler.ts
  addon/editor/input-handlers/text-input-handler.ts
  addon/editor/input-handlers/undo-handler.ts
  addon/model/controller.ts
  addon/model/model-position.ts
  addon/model/mutators/immediate-model-mutator.ts
  addon/model/util/constants.ts
  addon/model/writers/html-element-writer.ts
  addon/plugins/lump-node/lump-node.ts
  addon/utils/array-equals.ts
  addon/utils/ce/handlers/emphasis-markdown-handler.js
  addon/utils/ce/handlers/handler-response.js
  addon/utils/ce/handlers/header-markdown-handler.js
  addon/utils/ce/handlers/list-insertion-markdown-handler.js
  addon/utils/ce/handlers/tab-handler.js
  addon/utils/ce/list-helpers.ts
  addon/utils/ce/movement-observers/lump-node-movement-observer.ts
  addon/utils/ce/movement-observers/movement-observer.ts
  addon/utils/ce/pernet-raw-editor.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/plugins/anchor-tags/text-input-plugin.ts
  addon/utils/plugins/empty-element/backspace-plugin.ts
  addon/utils/plugins/empty-text-node/backspace-plugin.ts
  addon/utils/plugins/lists/backspace-plugin.ts
  addon/utils/plugins/lists/delete-plugin.ts
  addon/utils/plugins/lists/tab-input-plugin.ts
  addon/utils/plugins/lump-node/backspace-plugin.ts
  addon/utils/plugins/lump-node/tab-input-plugin.ts
  addon/utils/plugins/placeholder-text/backspace-plugin.ts
  addon/utils/plugins/placeholder-text/text-input-plugin.ts
  addon/utils/plugins/rdfa/backspace-plugin.ts
  addon/utils/plugins/rdfa/text-input-plugin.ts
  addon/utils/plugins/table/tab-input-plugin.ts
  tests/integration/input-handlers/plugins/list-delete-plugin-test.ts
  tests/test-utils.ts
Labels: enhancement

#262 feature/improved prefix handling
  addon/model/model-range.ts
  addon/model/util/datastore/datastore.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
  addon/utils/rdfa-parser/util.ts
Labels: enhancement
