Repository lblod/ember-rdfa-editor, pull requests merged in 2022-07, with the labels that each got.

#287 Article plugin styling
  app/styles/ember-rdfa-editor/_c-annotation-content-en.scss
  app/styles/ember-rdfa-editor/_c-annotation-content-nl.scss
  app/styles/ember-rdfa-editor/_c-annotation-hover.scss
  app/styles/ember-rdfa-editor/_c-content.scss
Labels: enhancement

#289 fixed issue where insert a list a the end of line caused the insertion of a newline
  addon/commands/make-list-command.ts
  tests/unit/commands/make-list-command-test.ts
Labels: bug

#290 Fix cursor behavior in empty lists
  addon/commands/make-list-command.ts
  package-lock.json
  tests/unit/commands/make-list-command-test.ts
Labels: bug

#295 Insert empty space when inserting an li above another one
  addon/commands/insert-newLi-command.ts
  tests/unit/commands/insert-new-li-command-test.ts
Labels: bug

#293 Null check on the parent of the range in live mark set
  addon/model/live-mark-set.ts
  addon/model/operations/mark-operation.ts
Labels: bug

#296 Remove erroneous check to avoid duplicate selectionchange events
  addon/model/writers/selection-writer.ts
  addon/utils/ce/model-selection-tracker.ts
Labels: bug

#294 when storing the previous selection, clone the anchor nodes
  addon/model/writers/selection-writer.ts
  addon/utils/ce/model-selection-tracker.ts
Labels: bug

#299 Enabling reload of plugins
  addon/components/ce/content-editable.hbs
  addon/components/ce/content-editable.ts
  addon/utils/ce/raw-editor.ts
Labels: enhancement

#288 Feature/tab handler vdom
  addon/components/rdfa/rdfa-editor.ts
  addon/config/sample-data.ts
  addon/editor/input-handlers/tab-handler.ts
  addon/model/controller.ts
  addon/model/model-position.ts
  addon/model/model.ts
  addon/model/util/array-utils.ts
  addon/model/util/gen-tree-walker.ts
  addon/model/util/model-node-utils.ts
  addon/model/util/types.ts
  addon/model/writers/selection-writer.ts
  addon/plugins/show-active-rdfa/show-active-rdfa.ts
  addon/utils/ce/raw-editor.ts
  addon/utils/editor-event.ts
  addon/utils/plugins/lists/tab-input-plugin.ts
  addon/utils/plugins/lump-node/tab-input-plugin.ts
  addon/utils/plugins/table/tab-input-plugin.ts
  app/styles/ember-rdfa-editor/_c-annotation.scss
Labels: enhancement

#302 Improve selection handler
  addon/input/input-handler.ts
  package-lock.json
Labels: internal

#304 Fix/lump node plugin selection
  addon/commands/node-properties/remove-property-command.ts
  addon/commands/node-properties/set-property-command.ts
  addon/plugins/lump-node/lump-node.ts
  addon/utils/plugins/lump-node/backspace-delete-plugin.ts
Labels: bug

#300 Replace ix by itertools
  addon/model/util/array-utils.ts
  addon/model/util/datastore/result-set.ts
  addon/model/util/datastore/term-mapping.ts
  addon/model/util/iterator-utils.ts
  addon/utils/plugins/lists/tab-input-plugin.ts
  package-lock.json
  package.json
Labels: internal

#303 Reduce selectionChanged events
  addon/model/model-position.ts
  addon/model/model-selection.ts
  addon/model/model.ts
Labels: bug
