Repository lblod/ember-rdfa-editor, pull requests merged in 2022-11, with the labels that each got.

#443 Refresh inline components after model read
  addon/components/rdfa/rdfa-editor.ts
Labels: bug

#444 Remove unnecessary read on mouseup
  addon/editor/input-handlers/fallback-input-handler.ts
Labels: internal

#454 fix(deps): use proper versions of the @types packages
  package-lock.json
  package.json
Labels: internal

#455 Inline components: serializable properties
  addon/commands/insert-component-command.ts
  addon/model/inline-components/inline-component-controller.ts
  addon/model/inline-components/model-inline-component.ts
  addon/model/readers/html-inline-component-reader.ts
  tests/dummy/app/components/inline-components-plugin/counter.hbs
  tests/dummy/app/components/inline-components-plugin/counter.ts
  tests/dummy/app/components/inline-components-plugin/dropdown.hbs
  tests/dummy/app/components/inline-components-plugin/dropdown.ts
  tests/dummy/app/components/inline-components-plugin/rdfa-ic-plugin-insert.hbs
  tests/dummy/app/components/inline-components-plugin/rdfa-ic-plugin-insert.ts
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/inline-component-models/counter.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/inline-component-models/dropdown.ts
  tests/dummy/app/dummy-plugins/inline-components-plugin/inline-components-plugin.ts
  tests/dummy/app/initializers/dummy-plugins.ts
Labels: enhancement, breaking

#456 Remove unnecessary read in htmlContent method
  addon/model/controller.ts
Labels: internal

#467 Enable model node size cache
  addon/core/model/nodes/model-node.ts
  addon/core/model/operations/operation-algorithms.ts
  addon/core/model/simple-position.ts
  addon/core/model/simple-range.ts
  addon/core/state/steps/mark-step.ts
  tests/test-utils.ts
  tests/unit/model/operations/algorithms/insert-algorithm-test.ts
  tests/unit/model/operations/algorithms/remove-algorithm-test.ts
  tests/unit/model/operations/algorithms/remove-new-algorithm-test.ts
  tests/unit/model/operations/algorithms/split-algorithm-test.ts
Labels: enhancement

#478 Get remove command working with immutability and fix issues with moveToPosition
  addon/commands/remove-command.ts
  addon/core/state/steps/attribute-step.ts
  addon/core/state/steps/insert-text-step.ts
  addon/core/state/steps/mark-step.ts
  addon/core/state/steps/remove-step.ts
  addon/core/state/steps/replace-step.ts
  addon/core/state/steps/split-step.ts
  addon/core/state/steps/step.ts
  addon/core/state/steps/wrap-step.ts
  addon/core/state/transaction.ts
  tests/unit/commands/remove-command-test.ts
  tests/unit/model/operations/move-operation-test.ts
Labels: bug

#468 Update ember-appuniversum to v2
  package-lock.json
  package.json
Labels: breaking

#481 fix(paste): preserve list indentation when copying from word
  addon/utils/ce/paste-handler-helper-functions/buildList.ts
  package-lock.json
  tests/unit/utils/convert-ms-word-html-test.ts
Labels: bug
