Repository lblod/ember-rdfa-editor, pull requests merged in 2022-01, with the labels that each got.

#204 allow browser delete if the feature flag is enabled
  addon/components/ce/content-editable.ts
  config/environment.js
Labels: enhancement

#205 Fix broken datastore in prod
  addon/model/util/gen-tree-walker.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
Labels: bug

#207 moved hints logic to the editor component so it gets tracked
  addon/components/rdfa/editor-suggested-hints.hbs
  addon/components/rdfa/editor-suggested-hints.js
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
Labels: bug

#200 bump docker ember image
  Dockerfile
Labels: internal

#206 Feature/gn 3152 create a debug component for the rdfa editor
  addon/components/rdfa/rdfa-editor-with-debug.hbs
  addon/components/rdfa/rdfa-editor-with-debug.ts
  addon/config/sample-data.ts
  addon/templates/components/rdfa/rdfa-editor-with-debug.hbs
  app/components/rdfa/rdfa-editor-with-debug.js
  package-lock.json
  package.json
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/index.hbs
Labels: enhancement
