Repository lblod/ember-rdfa-editor, pull requests merged in 2023-01, with the labels that each got.

#521 Ensure placeholders are non-draggable and use placeholder-text as leafText
  addon/nodes/placeholder.ts
  addon/utils/position-utils.ts
Labels: internal

#528 Lower priority of rdfa mark so it parses after the nodes
  addon/nodes/inline-rdfa.ts
Labels: bug

#530 feat(datastore): make datastore lazy
  addon/core/prosemirror.ts
  addon/plugins/datastore/index.ts
Labels: enhancement

#535 Add translation for 'insert' and 'show annotations' buttons.
  addon/components/rdfa/rdfa-editor.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#529 insert hard break as last resort on enter key
  addon/commands/insert-hard-break.ts
  addon/core/keymap.ts
  addon/core/prosemirror.ts
Labels: enhancement

#531 Support for subscript and superscript marks
  addon/components/plugins/subscript/button.hbs
  addon/components/plugins/subscript/button.ts
  addon/components/plugins/superscript/button.hbs
  addon/components/plugins/superscript/button.ts
  addon/plugins/subscript/index.ts
  addon/plugins/superscript/index.ts
  app/components/plugins/subscript/button.js
  app/components/plugins/superscript/button.js
  app/styles/ember-rdfa-editor/_c-content.scss
  package-lock.json
  package.json
  tests/dummy/app/controllers/index.ts
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#537 Remove context from parsing rule paragraph
  addon/nodes/paragraph.ts
Labels: bug

#532 Addition of a menu which allows to insert headings
  addon/commands/set-block-type.ts
  addon/components/plugins/headings/headings-menu.hbs
  addon/components/plugins/headings/headings-menu.ts
  addon/components/plugins/table/table-menu.hbs
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/toolbar-dropdown.hbs
  addon/components/rdfa/toolbar-dropdown.ts
  addon/plugins/headings/index.ts
  app/components/plugins/headings/headings-menu.js
  app/styles/ember-rdfa-editor/_c-dropdown.scss
  package-lock.json
  package.json
  tests/dummy/app/controllers/index.ts
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#540 update prosemirror packages to latest versions
  package-lock.json
  package.json
Labels: internal

#546 Set word-wrap as break-word on editor
  app/styles/ember-rdfa-editor/_c-editor.scss
Labels: bug

#547 Pass view to ember-node as property
  addon/index.ts
  addon/utils/ember-node.ts
Labels: enhancement

#548 feat(datastore): add a special static context-store for the rdfa outside of the editor
  addon/core/prosemirror.ts
  addon/plugins/datastore/index.ts
  addon/utils/rdfa-parser/rdfa-parser.ts
Labels: enhancement

#551 Make parsing rules of lists and paragraphs non consuming
  addon/nodes/list-nodes.ts
  addon/nodes/paragraph.ts
Labels: bug

#552 Make paragraphs not parse when they contain rdfa
  addon/nodes/block-rdfa.ts
  addon/nodes/paragraph.ts
Labels: enhancement

#553 Add functionality to support an embedded view and allow widgets to perform actions on either the outer or inner view
  addon/components/plugins/subscript/button.ts
  addon/components/plugins/superscript/button.ts
  addon/components/plugins/table/table-menu.hbs
  addon/components/rdfa/editor-toolbar.ts
  addon/core/prosemirror.ts
  addon/index.ts
Labels: enhancement

#555 Rework set-html-content function to ensure no extra paragraphs are added
  addon/core/prosemirror.ts
Labels: bug

#557 fix(commands): focus the editor after inserting html
  addon/commands/insert-html-command.ts
Labels: bug

#560 Add redo button
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/editor-toolbar.ts
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#561 fix delete behavior in front of table
  addon/plugins/table/index.ts
  addon/plugins/table/table.ts
  app/styles/ember-rdfa-editor/_c-table.scss
Labels: bug

#562 Remove ember-instance from window and pass it through for ember-nodes
  addon/components/rdfa/rdfa-editor.ts
  addon/core/prosemirror.ts
  addon/utils/ember-node.ts
  types/window.d.ts
Labels: internal

#563 Improve performance drastically by using the overflow: scroll css-rule
  app/styles/ember-rdfa-editor/_c-container.scss
Labels: enhancement

#566 Ensure delete and backspace behaviour around tables is consistent
  addon/commands/select-parent-node-of-type.ts
  addon/core/keymap.ts
  package-lock.json
  package.json
Labels: bug

#567 chore(deps): remove ember-cli-coverage
  package-lock.json
  package.json
Labels: internal
