Repository lblod/ember-rdfa-editor, pull requests merged in 2023-02, with the labels that each got.

#564 Add end position to find-nodes function
  addon/utils/position-utils.ts
  tests/unit/utils/position-utils-test.ts
Labels: enhancement, breaking

#568 Upgrade ember-source to 4.8.4
  .drone.yml
  .ember-cli
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .prettierignore
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  README.md
  config/ember-try.js
  package-lock.json
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
Labels: internal

#583 Fix wrapping of spaces at line end
  CHANGELOG.md
  app/styles/ember-rdfa-editor/_c-editor.scss
Labels: bug

#594 feat(nodespecs): support a canSplit property in nodespecs which is checked on enter keypress
  CHANGELOG.md
  addon/commands/lift-empty-block-checked.ts
  addon/commands/split-block-checked.ts
  addon/core/keymap.ts
Labels: enhancement

#593 Remove whitespace css rule on say-table to allow spaces inside table cells
  CHANGELOG.md
  app/styles/ember-rdfa-editor/_c-table.scss
Labels: bug

#596 Preserve whitespace when parsing an html document
  addon/core/prosemirror.ts
Labels: bug

#601 Add ordered list feature
  CHANGELOG.md
  addon/commands/toggle-list.ts
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/rdfa-editor.hbs
  addon/components/rdfa/rdfa-editor.ts
  app/styles/ember-rdfa-editor/_c-content.scss
  tests/dummy/app/templates/index.hbs
Labels: enhancement

#598 Add plugin to auto generate attributes when they are missing
  CHANGELOG.md
  addon/components/rdfa/rdfa-editor-with-debug.hbs
  addon/components/rdfa/rdfa-editor-with-debug.ts
  addon/components/rdfa/rdfa-editor.ts
  addon/core/prosemirror.ts
  addon/plugins/default-attribute-value-generation/index.ts
  addon/utils/changed-descendants.ts
Labels: enhancement

#611 Rework link handler a bit to prevent range errors
  addon/plugins/links/index.ts
Labels: bug

#610 Add tab key handler to indent/unindent list items
  CHANGELOG.md
  addon/core/keymap.ts
Labels: enhancement

#622 Replace drone by woodpecker
  .drone.yml
  .woodpecker/.build-pr.yml
  .woodpecker/.ember-scenarios.yml
  .woodpecker/.latest.yml
  .woodpecker/.release.yml
  .woodpecker/.verify-pr.yml
  CHANGELOG.md
Labels: internal

#616 disabled undo and redo button when there's no more steps
  CHANGELOG.md
  addon/components/rdfa/editor-toolbar.hbs
  addon/components/rdfa/editor-toolbar.ts
  addon/components/rdfa/toolbar-icon.hbs
  app/styles/ember-rdfa-editor/_c-toolbar.scss
Labels: enhancement

#617 Replace text marks in another way in attribute generation plugin to fix cursor jumping
  CHANGELOG.md
  addon/plugins/default-attribute-value-generation/index.ts
Labels: bug

#632 Keep selection on the document when toggling annotations
  CHANGELOG.md
  addon/components/editor-container.hbs
  addon/components/editor.ts
  addon/components/plugins/rdfa-block-render/rdfa-blocks-toggle.ts
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/templates/index.hbs
Labels: bug

#619 Rework controller methods which are used to access the different editor views.
  CHANGELOG.md
  addon/components/ember-node/embedded-editor.ts
  addon/components/plugins/heading/heading-menu.ts
  addon/components/plugins/history/redo.ts
  addon/components/plugins/history/undo.ts
  addon/components/plugins/list/indentation-controls.ts
  addon/components/plugins/list/ordered.ts
  addon/components/plugins/list/unordered.ts
  addon/components/sidebar/link-editor.ts
  addon/components/toolbar/mark.hbs
  addon/components/toolbar/mark.ts
  addon/core/say-controller.ts
  addon/core/say-editor.ts
  addon/core/say-view.ts
  addon/utils/_private/ember-node.ts
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/controllers/plugins.ts
Labels: breaking

#618 Addition of margin on elements below paragraphs and tables
  CHANGELOG.md
  app/styles/ember-rdfa-editor/_c-content.scss
Labels: enhancement

#626 Modernize toolbar dropdown
  CHANGELOG.md
  addon/components/toolbar/dropdown.hbs
  addon/components/toolbar/dropdown.ts
Labels: internal

#634 ensure that a node-selection is recreated when updating the markup of a node in de attribute-generation-plugin
  addon/plugins/default-attribute-value-generation/index.ts
Labels: bug

#635 Update ember-appuniversum to 2.4.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#641 Allow users to set a cursor by clicking in the margin of the editor
  CHANGELOG.md
  app/styles/ember-rdfa-editor/_c-editor.scss
Labels: enhancement

#642 Fix shrinking issues with toolbar buttons and dropdowns
  CHANGELOG.md
  app/styles/ember-rdfa-editor/_c-dropdown.scss
  app/styles/ember-rdfa-editor/_c-toolbar.scss
Labels: bug

#607 Improved link support
  CHANGELOG.md
  addon/commands/wrap-selection.ts
  addon/components/ember-node/embedded-editor.hbs
  addon/components/ember-node/embedded-editor.ts
  addon/components/ember-node/link.hbs
  addon/components/ember-node/link.ts
  addon/components/plugins/heading/heading-menu.ts
  addon/components/plugins/history/redo.ts
  addon/components/plugins/history/undo.ts
  addon/components/plugins/link/link-editor.hbs
  addon/components/plugins/link/link-editor.ts
  addon/components/plugins/link/link-menu.hbs
  addon/components/plugins/link/link-menu.ts
  addon/components/plugins/list/indentation-controls.ts
  addon/components/plugins/list/ordered.ts
  addon/components/plugins/list/unordered.ts
  addon/components/toolbar/mark.hbs
  addon/components/toolbar/mark.ts
  addon/components/utils/au-pill-dropdown.hbs
  addon/components/utils/au-pill-dropdown.ts
  addon/core/say-controller.ts
  addon/core/say-editor.ts
  addon/core/say-view.ts
  addon/nodes/link.ts
  addon/utils/_private/ember-node.ts
  app/components/embedded-editor.js
  app/components/ember-node/embedded-editor.js
  app/components/ember-node/link.js
  app/components/link.js
  app/components/plugins/link/link-editor.js
  app/components/plugins/link/link-menu.js
  app/components/toolbar/list-menu.js
  app/components/utils/au-pill-dropdown.js
  app/styles/ember-rdfa-editor/_a-custom-components.scss
  app/styles/ember-rdfa-editor/_c-link.scss
  app/styles/ember-rdfa-editor/_c-placeholder.scss
  package-lock.json
  package.json
  tests/dummy/app/components/sample-toolbar.hbs
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/controllers/plugins.ts
  tests/dummy/app/templates/index.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#621 Added features to add table headings
  CHANGELOG.md
  addon/components/plugins/table/table-menu.hbs
  addon/components/plugins/table/table-menu.ts
  app/styles/ember-rdfa-editor/_c-table.scss
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#643 Addition of paragraph/heading indentation
  CHANGELOG.md
  addon/commands/indent-node.ts
  addon/commands/index.ts
  addon/components/plugins/indentation/indentation-menu.hbs
  addon/components/plugins/indentation/indentation-menu.ts
  addon/components/plugins/list/indentation-controls.ts
  addon/nodes/paragraph.ts
  addon/plugins/heading/nodes/heading.ts
  app/components/plugins/indentation/indentation-menu.js
  app/styles/ember-rdfa-editor/_c-content.scss
  tests/dummy/app/components/sample-toolbar.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#656 Add padding to rdfa-toggle and add flex-shrink:0 to toolbar-group
  CHANGELOG.md
  addon/components/plugins/rdfa-block-render/rdfa-blocks-toggle.hbs
  app/styles/ember-rdfa-editor/_c-toolbar.scss
Labels: bug
