Repository lblod/ember-rdfa-editor, pull requests merged in 2023-09, with the labels that each got.

#955 GN-4479: allow for option to pass nodeviews object to embedded-editor component
  .changeset/proud-eyes-hammer.md
  addon/components/ember-node/embedded-editor.ts
Labels: enhancement

#960 Removal of dependabot changelog workflow
  .changeset/brown-sheep-shave.md
  .github/workflows/dependabot-changelog.yml
Labels: internal

#957 GN-4479: fix issues with embedded editor inner dispatch
  .changeset/eleven-adults-call.md
  addon/components/ember-node/embedded-editor.ts
Labels: bug

#963 Provide a Webpack config object
  .changeset/happy-gifts-train.md
  .eslintrc.js
  README.md
  ember-cli-build.js
  index.js
  webpack-config.js
Labels: enhancement

#961 Replace `ember-get-config` with `@embroider/macros`
  .changeset/weak-shirts-wink.md
  addon/utils/_private/logging-utils.ts
  package-lock.json
  package.json
  types/global.d.ts
Labels: internal

#964 Embroider optimized support
  .changeset/old-avocados-jam.md
  README.md
  addon/components/ember-node/link.hbs
  addon/components/ember-node/link.ts
  addon/components/plugins/text-style/color.hbs
  addon/components/plugins/text-style/color.ts
  addon/components/plugins/text-style/highlight.hbs
  addon/components/plugins/text-style/highlight.ts
  addon/components/responsive-toolbar.hbs
  addon/components/responsive-toolbar.ts
  addon/components/toolbar/dropdown.hbs
  addon/components/toolbar/dropdown.ts
  addon/plugins/image/nodes/image.ts
  addon/plugins/link/nodes/link.ts
  addon/utils/_private/ember-node.ts
  package-lock.json
  package.json
  tests/dummy/app/components/sample-ember-nodes/card.ts
  tests/dummy/app/dummy-nodes/card.ts
  tests/dummy/app/dummy-nodes/counter.ts
  tests/dummy/app/dummy-nodes/dropdown.ts
  tests/test-utils.ts
Labels: breaking

#959 Move changeset check to seperate CI pipeline
  .changeset/sweet-moons-obey.md
  .woodpecker/.changeset.yml
  .woodpecker/.verify-pr.yml
Labels: internal

#971 Fix `when` statement of changeset CI pipeline
  .woodpecker/.changeset.yml
Labels: internal
