Repository lblod/ember-rdfa-editor, pull requests merged in 2025-04, with the labels that each got.

#1283 Convert release-commit pipeline to manual pipeline
  .woodpecker/.release-commit.yml
Labels: internal

#1286 CIT-31: rdfa tools tab behaviour/submit shortcuts
  .changeset/legal-fans-push.md
  .changeset/slow-rules-teach.md
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/external-triple-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/external-triple-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/wrapping-utils/modal.gts
Labels: enhancement

#1285 Feature/rdfa tools improvements
  .changeset/legal-fans-push.md
  .changeset/slow-rules-teach.md
  .changeset/thick-cows-bathe.md
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/external-triple-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/external-triple-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/wrapping-utils/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/wrapping-utils/modal.gts
  test-app/app/controllers/editable-node.ts
  test-app/app/templates/editable-node.hbs
Labels: enhancement

#1289 bugfix: remove usage of explicit `uniqueId` imports
  .changeset/silent-spoons-hope.md
  packages/ember-rdfa-editor/src/components/_private/attribute-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/doc-imported-resource-editor/form.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/form.gts
Labels: bug

#1295 fix(tooling): run build script before start scripts
  package.json
Labels: bug

#1294 feat: add yup-based validation to backlink-editor form
  .changeset/thirty-lemons-show.md
  packages/ember-rdfa-editor/package.json
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/form.gts
  pnpm-lock.yaml
Labels: enhancement

#1298 tooling: add simple dev-release script
  .woodpecker/.dev-release.yml
  .woodpecker/.release.yml
  package.json
  scripts/dev-release/run.mts
  scripts/release/utils.mts
Labels: internal

#1300 fix(ember-velcro): use absolute positioning
  .changeset/silent-flies-heal.md
  packages/ember-rdfa-editor/src/components/ember-node/link.hbs
  packages/ember-rdfa-editor/src/components/plugins/alignment/alignment-menu.hbs
  packages/ember-rdfa-editor/src/components/plugins/table/color.hbs
  packages/ember-rdfa-editor/src/components/plugins/table/vertical-align.hbs
  packages/ember-rdfa-editor/src/components/plugins/text-style/color.hbs
  packages/ember-rdfa-editor/src/components/plugins/text-style/highlight.hbs
  packages/ember-rdfa-editor/src/components/responsive-toolbar.hbs
  pnpm-lock.yaml
Labels: bug
