Repository lblod/ember-rdfa-editor, pull requests merged in 2025-05, with the labels that each got.

#1305 Add width rules to dynamic editor toolbar dropdowns
  .changeset/all-streets-pick.md
  packages/ember-rdfa-editor/scss/_c-toolbar.scss
Labels: bug

#1313 Convert responsive-toolbar to gts
  packages/ember-rdfa-editor/src/components/responsive-toolbar.gts
  packages/ember-rdfa-editor/src/components/responsive-toolbar.hbs
  packages/ember-rdfa-editor/src/components/toolbar/button.ts
  packages/ember-rdfa-editor/src/components/toolbar/divider.gts
  packages/ember-rdfa-editor/src/components/toolbar/divider.hbs
  packages/ember-rdfa-editor/src/components/toolbar/group.gts
  packages/ember-rdfa-editor/src/components/toolbar/group.hbs
Labels: no-changeset

#1308 Fix non existing rdfa id issues
  .changeset/cyan-lemons-shine.md
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/form.gts
  packages/ember-rdfa-editor/src/plugins/rdfa-info/utils.ts
  packages/ember-rdfa-editor/translations/en-us.yaml
  packages/ember-rdfa-editor/translations/nl-BE.yaml
Labels: bug

#1312 Standardize/reduce size of rdfa-tool cards
  .changeset/afraid-bushes-stand.md
  packages/ember-rdfa-editor/src/components/_private/attribute-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/debug-info/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/backlink-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/doc-imported-resource-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/external-triple-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/property-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-visualiser/rdfa-explorer.gts
  packages/ember-rdfa-editor/src/components/_private/rdfa-visualiser/visualiser-card.gts
  test-app/app/templates/editable-node.hbs
Labels: enhancement

#1309 intl(test-app): dynamically import intl files
  packages/ember-rdfa-editor/package.json
  packages/ember-rdfa-editor/translations/nl-be.yaml
  pnpm-lock.yaml
  test-app/app/routes/application.ts
  test-app/config/ember-intl.js
  test-app/package.json
  test-app/vite.config.mjs
Labels: enhancement

#1316 CIT-35: relationship-editor `document` config
  .changeset/floppy-shirts-tickle.md
  packages/ember-rdfa-editor/package.json
  packages/ember-rdfa-editor/src/components/_private/relationship-editor/configs.ts
  test-app/app/controllers/editable-node.ts
Labels: enhancement
