Repository lblod/ember-rdfa-editor, pull requests merged in 2025-02, with the labels that each got.

#1241 GN-5171: drop support for legacy rdfa-annotations
  .changeset/rude-pigs-lick.md
  .changeset/thin-toys-hide.md
  .changeset/wise-taxis-drive.md
  .woodpecker/.e2e.yml
  .woodpecker/.release-commit.yml
  .woodpecker/.release.yml
  .woodpecker/.test-compat-4.12.yml
  .woodpecker/.test-compat-embroider-optimized.yml
  .woodpecker/.test-compat-release.yml
  .woodpecker/.verify-pr.yml
  Dockerfile
  README.md
  addon/components/editor-container.gts
  addon/components/editor-container.hbs
  addon/components/plugins/rdfa-block-render/rdfa-blocks-toggle.hbs
  addon/components/plugins/rdfa-block-render/rdfa-blocks-toggle.ts
  addon/core/say-controller.ts
  addon/core/say-editor.ts
  app/styles/ember-rdfa-editor/_a-custom-components.scss
  app/styles/ember-rdfa-editor/_c-annotation-content-en.scss
  app/styles/ember-rdfa-editor/_c-annotation-content-nl.scss
  app/styles/ember-rdfa-editor/_c-annotation-flag.scss
  app/styles/ember-rdfa-editor/_c-annotation-hover.scss
  app/styles/ember-rdfa-editor/_c-annotation.scss
  app/styles/ember-rdfa-editor/_c-block-rdfa.scss
  app/styles/ember-rdfa-editor/_c-content.scss
  app/styles/ember-rdfa-editor/_c-editor.scss
  app/styles/ember-rdfa-editor/_c-inline-rdfa.scss
  app/styles/ember-rdfa-editor/_c-placeholder.scss
  tests/dummy/app/components/sample-toolbar-responsive.hbs
  tests/dummy/app/components/sample-toolbar.hbs
  tests/dummy/app/controllers/editable-node.ts
  tests/dummy/app/controllers/index.ts
  tests/dummy/app/controllers/space-invisible.ts
  tests/dummy/app/templates/editable-node.hbs
  tests/dummy/app/templates/index.hbs
  tests/dummy/app/templates/plugins.hbs
  tests/dummy/app/templates/space-invisible.hbs
Labels: breaking

#1248 allow inline images with config and checkPasteSize plugin
  .changeset/rude-eagles-help.md
  addon/plugins/image/index.ts
  addon/plugins/image/nodes/image.ts
  addon/plugins/image/plugins/checkPasteSize.ts
  tests/dummy/app/controllers/index.ts
Labels: enhancement

#1251 add test for remove-properties plugin
  .woodpecker/.changeset.yml
  tests/test-utils.ts
  tests/unit/prosemirror/external-triple-test.ts
  tests/unit/prosemirror/remove-properties-of-deleted-nodes-test.ts
  tests/utils/editor.ts
Labels: no-changeset

#1254 internal: restructure test helpers
  test-app/tests/helpers/common.ts
  test-app/tests/helpers/datastore.ts
  test-app/tests/helpers/index.js
  test-app/tests/helpers/prosemirror.ts
  test-app/tests/helpers/qunit/assertions.ts
  test-app/tests/helpers/qunit/parsers.ts
  test-app/tests/helpers/say-editor.ts
  test-app/tests/integration/rdfa/blackbox-test.ts
  test-app/tests/test-helper.ts
  test-app/tests/test-utils.ts
  test-app/tests/unit/prosemirror/external-triple-test.ts
  test-app/tests/unit/prosemirror/marks-test.ts
  test-app/tests/unit/prosemirror/remove-properties-of-deleted-nodes-test.ts
  test-app/tests/unit/prosemirror/view-test.ts
  test-app/tests/unit/rdfa/rdfa-parsing-test.ts
  test-app/tests/unit/utils/position-utils-test.ts
Labels: internal

#1259 Tweaks to the v2 addon set-up
  README.md
  package.json
  packages/ember-rdfa-editor/package.json
  packages/ember-rdfa-editor/src/plugins/datastore/index.ts
  packages/ember-rdfa-editor/src/utils/_private/rdfa-utils.ts
  pnpm-lock.yaml
  test-app/package.json
Labels: no-changeset

#1261 pin prosemirror-history package to 1.4.1
  .changeset/shiny-scissors-complain.md
  packages/ember-rdfa-editor/package.json
  pnpm-lock.yaml
Labels: internal

#1256 GN-5413: support for persisting `collapsable` state of collapsable menus/sections
  .changeset/eighty-keys-drum.md
  .changeset/nice-months-complain.md
  .changeset/perfect-trainers-judge.md
  .changeset/real-feet-share.md
  .changeset/red-avocados-thank.md
  .changeset/silent-peas-travel.md
  .changeset/sixty-bananas-jog.md
  .changeset/soft-seas-know.md
  packages/ember-rdfa-editor/src/components/_private/attribute-editor/index.gts
  packages/ember-rdfa-editor/src/components/_private/attribute-editor/index.hbs
  packages/ember-rdfa-editor/src/components/_private/attribute-editor/index.ts
  packages/ember-rdfa-editor/src/components/_private/debug-info/index.gts
  packages/ember-rdfa-editor/src/components/_private/debug-info/index.hbs
  packages/ember-rdfa-editor/src/components/_private/debug-info/index.ts
  packages/ember-rdfa-editor/src/components/_private/doc-editor/info-pill.ts
  packages/ember-rdfa-editor/src/components/_private/rdfa-editor/index.gts
  packages/ember-rdfa-editor/src/components/collapsible.gts
  packages/ember-rdfa-editor/src/components/collapsible.hbs
  packages/ember-rdfa-editor/src/components/collapsible.ts
  packages/ember-rdfa-editor/src/components/sidebar.gts
  packages/ember-rdfa-editor/src/components/sidebar.hbs
  packages/ember-rdfa-editor/src/components/sidebar.ts
  test-app/app/components/dummy-container.hbs
  test-app/app/components/sample-ember-nodes/sidebar-insert.hbs
  test-app/app/components/sample-ember-nodes/sidebar-insert.ts
  test-app/app/components/sample-ember-nodes/sidebar.gts
  test-app/app/controllers/plugins.ts
  test-app/app/templates/plugins.hbs
Labels: enhancement

#1263 fix(html-input-parser): return correct htmlelement
  .changeset/tricky-glasses-fail.md
  packages/ember-rdfa-editor/src/core/say-editor.ts
  packages/ember-rdfa-editor/src/utils/_private/html-input-parser.ts
Labels: bug

#1265 GN-5480: use SASS scoped imports
  .changeset/sour-wombats-compare.md
  packages/ember-rdfa-editor/scss/_c-block-rdfa.scss
  packages/ember-rdfa-editor/scss/_c-container.scss
  packages/ember-rdfa-editor/scss/_c-content.scss
  packages/ember-rdfa-editor/scss/_c-dropdown.scss
  packages/ember-rdfa-editor/scss/_c-dummy.scss
  packages/ember-rdfa-editor/scss/_c-editor-hints.scss
  packages/ember-rdfa-editor/scss/_c-editor.scss
  packages/ember-rdfa-editor/scss/_c-icon.scss
  packages/ember-rdfa-editor/scss/_c-image.scss
  packages/ember-rdfa-editor/scss/_c-inline-rdfa.scss
  packages/ember-rdfa-editor/scss/_c-link.scss
  packages/ember-rdfa-editor/scss/_c-placeholder.scss
  packages/ember-rdfa-editor/scss/_c-selection-tooltip.scss
  packages/ember-rdfa-editor/scss/_c-table.scss
  packages/ember-rdfa-editor/scss/_c-toast.scss
  packages/ember-rdfa-editor/scss/_c-toolbar.scss
  packages/ember-rdfa-editor/scss/_shame.scss
Labels: bug

#1264 Fix hot reloading in the test app
  .changeset/sour-wombats-compare.md
  .npmrc
  Dockerfile
  package.json
  packages/ember-rdfa-editor/scss/_c-block-rdfa.scss
  packages/ember-rdfa-editor/scss/_c-container.scss
  packages/ember-rdfa-editor/scss/_c-content.scss
  packages/ember-rdfa-editor/scss/_c-dropdown.scss
  packages/ember-rdfa-editor/scss/_c-dummy.scss
  packages/ember-rdfa-editor/scss/_c-editor-hints.scss
  packages/ember-rdfa-editor/scss/_c-editor.scss
  packages/ember-rdfa-editor/scss/_c-icon.scss
  packages/ember-rdfa-editor/scss/_c-image.scss
  packages/ember-rdfa-editor/scss/_c-inline-rdfa.scss
  packages/ember-rdfa-editor/scss/_c-link.scss
  packages/ember-rdfa-editor/scss/_c-placeholder.scss
  packages/ember-rdfa-editor/scss/_c-selection-tooltip.scss
  packages/ember-rdfa-editor/scss/_c-table.scss
  packages/ember-rdfa-editor/scss/_c-toast.scss
  packages/ember-rdfa-editor/scss/_c-toolbar.scss
  packages/ember-rdfa-editor/scss/_shame.scss
  pnpm-lock.yaml
  test-app/package.json
  test-app/tests/test-helper.ts
Labels: no-changeset
